
services:
  frontend:
    image: 127.0.0.1:5000/frontend_image
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  backend:
    image: 127.0.0.1:5000/backend_image
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
